; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; 错误代码:
; -1:存档目录获取失败
; -2:游戏目录获取失败
; -3:游戏Bank写入失败
; -4:游戏存档声音写入失败
; -10:安装残留清除失败
#define MyAppName "ts-fmod-plugin"
#define MyAppVersion "1.50.7.0"
#define MyAppPublisher "dariowouters&SmallHy"
#define MyAppURL "https://github.com/dariowouters/ts-fmod-plugin"
#include "Plugin\DllsImport.iss"
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EB59022F-93F0-40E4-8C82-413B4DB52BDF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=D:\SteamLibrary\steamapps\common\Euro Truck Simulator 2\
DefaultGroupName={#MyAppName}
ArchitecturesInstallIn64BitMode=x64os
DisableProgramGroupPage=yes
InfoBeforeFile=F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\License\License.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=F:\Tool\Inno Setup 6\Output
OutputBaseFilename=[线上可用]TruckersMP声音导航_v1.50.7.0_v1.50.4.0s
SetupIconFile=F:\Tool\Inno Setup 6\Input\Logo\Tmp.ico
Compression=lzma
SolidCompression=yes
UninstallFilesDir="{app}\bin\win_x64\plugins\ts-fmod-plugin\Uninst"
WizardStyle=modern
WizardImageFile=F:\Tool\Inno Setup 6\Input\Logo\TmpLogo.bmp
UsePreviousAppDir=yes
DirExistsWarning=no

[Languages]
Name: "ChineseSimplified"; MessagesFile: "compiler:Languages\Euro Turck Simulator 2\ChineseSimplified.isl"
Name: "ChineseTraditional"; MessagesFile: "compiler:Languages\Euro Turck Simulator 2\ChineseTraditional.isl"
Name: "English"; MessagesFile: "compiler:Languages\Euro Turck Simulator 2\English.isl"

[Messages]
SelectDirDesc= 
SelectDirLabel3=请选择_Steam游戏库_主目录[必须包含Euro Truck Simulator 2 文件夹]
SelectDirBrowseLabel=例如:_SteamLibrary\steamapps\common\

[Components]
Name: Main; Description:"主程序(必选)";Types:full compact custom;Flags: fixed
Name: Option; Description:"→卡车引擎声音←";Types:compact custom;Flags: fixed;
Name: Option; Description:"无";Types:compact custom;Flags: exclusive;
Name: HySuperV8; Description:"小虎牙V8引擎声音(可选)";Flags: exclusive;
Name: DafEngine; Description:"达夫(Daf)引擎声音(可选)";Flags: exclusive;
Name: RenaultEngine; Description:"雷诺(Renault)引擎声音(可选)";Flags: exclusive;
Name: Scania_DC12; Description:"斯堪尼亚(Scania)_DC12引擎声音(可选)";Flags: exclusive;
Name: Scania_DC124; Description:"斯堪尼亚(Scania)_DC124引擎声音(可选)";Flags: exclusive;
Name: Scania_v8; Description:"斯堪尼亚(Scania)_v8引擎声音(可选)";Flags: exclusive;
Name: Volvo_Vnl; Description:"沃尔沃(Volvo)引擎声音(可选)";Flags: exclusive
Name: Option; Description:"→卡车内部声音←";Types:compact custom;Flags: fixed;
Name: Option; Description:"无";Types:compact custom;Flags: exclusive;
Name: HyInteralSound; Description:"小虎牙内部声音(可选)";Flags: exclusive;
Name: Option; Description:"→卡车语音导航←";Types:compact custom;Flags: fixed;
Name: Option; Description:"无";Types:compact custom;Flags: exclusive;
Name: Option; Description:"→地方方言←";Flags: exclusive;
Name: DongbeiMM; Description:"导航东北美眉(可选)";Flags: exclusive;
Name: Option; Description:"→视频人物←";Flags: exclusive;
Name: Tianmilaozhang; Description:"导航甜蜜老张(可选)";Flags: exclusive;
Name: Option; Description:"→电影人物←";Flags: exclusive;
Name: Chenshuting; Description:"导航陈舒婷(可选)";Flags: exclusive;
Name: Guodegang; Description:"导航郭德纲(可选)";Flags: exclusive;
Name: Luoyonghao; Description:"导航罗永浩(可选)";Flags: exclusive;
Name: Shenteng; Description:"导航沈腾(可选)";Flags: exclusive;
Name: Suisui; Description:"导航穗穗(可选)";Flags: exclusive;
Name: Xujiang; Description:"导航徐江(可选)";Flags: exclusive;
Name: Yuqian; Description:"导航于谦(可选)";Flags: exclusive;
Name: Option; Description:"→火爆歌手←";Flags: exclusive;
Name: LeZhengLing; Description:"导航乐正凌(可选)";Flags: exclusive;
Name: Wuren; Description:"导航五人(可选)";Flags: exclusive;
Name: Xiangwan; Description:"导航向晚(可选)";Flags: exclusive;
Name: Option; Description:"→声甜萌妹←";Flags: exclusive;
Name: Bingtang; Description:"导航冰糖(可选)";Flags: exclusive;
Name: Luotianyi; Description:"导航洛天依(可选)";Flags: exclusive
Name: Linzhiling; Description:"导航林志玲(可选)";Flags: exclusive
Name: Linzhiling_v2; Description:"导航林志玲v2(可选)";Flags: exclusive
Name: Shantu; Description:"导航山兔(可选)";Flags: exclusive;
Name: ShaonianPi; Description:"导航少年Pi(可选)";Flags: exclusive;
Name: Xiaotuantuan; Description:"导航小团团(可选)";Flags: exclusive
Name: Option; Description:"→原神←";Flags: exclusive;
Name: Keli; Description:"导航可莉(可选)";Flags: exclusive;
Name: Moli; Description:"导航茉莉(可选)";Flags: exclusive;
Name: Paimeng; Description:"导航派蒙(可选)";Flags: exclusive;
Name: Qin; Description:"导航·琴(可选)";Flags: exclusive; 

[Files]
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Bin\*"; DestDir: "{app}\bin"; Components:Main; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\HySuperV8\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:HySuperV8; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\HyInteralSound\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:HyInteralSound; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Daf\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:DafEngine; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Renault\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:RenaultEngine; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Scania_DC12\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Scania_DC12; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Scania_DC124\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Scania_DC124; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Scania_v8\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Scania_v8; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Engine\Default\Volvo_Vnl\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Volvo_Vnl; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Bingtang\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Bingtang; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Chenshuting\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Chenshuting; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\DongbeiMM\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:DongBeiMM; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Guodegang\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Guodegang; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Keli\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Keli; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Lezhengling\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Lezhengling; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Linzhiling\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Linzhiling; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Linzhiling_v2\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Linzhiling_v2; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Luotianyi\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Luotianyi; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Luoyonghao\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Luoyonghao; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Moli\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Moli; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Paimeng\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Paimeng; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Qin\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Qin; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Shantu\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Shantu; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\ShaonianPi\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:ShaonianPi; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Shenteng\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Shenteng; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Suisui\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Suisui; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Tianmilaozhang\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Tianmilaozhang; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Wuren\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Wuren; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Xiangwan\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Xiangwan; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Xiaotuantuan\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Xiaotuantuan; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Xujiang\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Xujiang; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Game\Nav\Yuqian\*"; DestDir: "{app}\bin\win_x64\plugins\ts-fmod-plugin"; Components:Yuqian; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Background\Media\BackgroundMusic.mp3"; Flags: dontcopy
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Batch\*"; Flags: dontcopy
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\License\License.txt"; Flags: dontcopy
Source: "F:\Tool\Inno Setup 6\Input\Euro Truck Simulator 2\Texture\Audio\*"; Flags: dontcopy
Source: compiler:Plugin\*; Flags: dontcopy noencryption
Source: compiler:psvince.dll; Flags: dontcopy noencryption
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Code]
//...............................................................//
//                            _ooOoo_                            //
//                           o8888888o                           //
//                           88" . "88                           //
//                           (| -_- |)                           //
//                            O\ = /O                            //
//                        ____/`---'\____                        //
//                      .   ' \\| |// `.                         //
//                       / \\||| 8 |||// \                       //
//                     / _||||| -8- |||||- \                     //
//                       | | \\\ 8 /// | |                       //
//                     | \_| ''\-8-/'' | |                       //
//                      \ .-\__ `8` ___/-. /                     //
//                   ___`. .' /--8--\ `. . __                    //
//                ."" '< `.___\_<8>_/___.' >'"".                 //
//               | | : `- \`.;`\ 8 /`;.`/ - ` : | |              //
//                 \ \ `-. \_ __\ /__ _/ .-` / /                 //
//         ======`-.____`-.___\_____/___.-`____.-'======         //
//                            `=---='                            //
//                                                               //
//...............................................................//
//变量定义

//自定义变量
type
  TDirectShowEventProc = procedure(EventCode, Param1, Param2: Integer);
  
//常数定义
const
  EC_COMPLETE = $01;
  
//前置接口
procedure OnEmbeddedMediaPlayerEvent(EventCode, Param1, Param2: Integer); 
begin
  if EventCode = EC_COMPLETE then
    MsgBox('Playback is done!', mbInformation, MB_OK);
end;
//函数块[1]:音乐播放器
function DSInitializeAudioFile(FileName: WideString; CallbackProc: TDirectShowEventProc): Boolean; 
  external 'DSInitializeAudioFile@files:mediaplayer.dll stdcall';
function DSPlayMediaFile: Boolean;
  external 'DSPlayMediaFile@files:mediaplayer.dll stdcall';
function DSStopMediaPlay: Boolean;
  external 'DSStopMediaPlay@files:mediaplayer.dll stdcall';
function DSSetVolume(Value: LongInt): Boolean;
  external 'DSSetVolume@files:mediaplayer.dll stdcall';
function DSGetLastError(var ErrorText: WideString): HRESULT;
  external 'DSGetLastError@files:mediaplayer.dll stdcall';
//函数块[2]:获取游戏目录
function SearthGamePath(RootKey: Integer; SubKeyName, ValueName: String; var OutInstallPath: String): Boolean;
var
InstallPath: String;
begin
  if RegValueExists(RootKey, SubKeyName, ValueName) then
  begin
    if RegQueryStringValue(RootKey, SubKeyName, ValueName, InstallPath) then
    begin
      OutInstallPath:= InstallPath;
      Result:= True;
      Exit;
    end
    else
    begin
      Result:= False;
      MsgBox('无法访问', mbError, MB_OK);
      Exit;
    end;
  end
  else
  begin
    Result:= False;
  end;
end;
//函数块[3]:检查目录
function CheakDir(InstallPath:String): Boolean; 
var 
   ExePath: String; 
begin 
  ExePath := InstallPath;
  if not FileExists(ExePath) then 
  begin 
    Result := False;
  end
  else
  begin
    Result := True;
  end;
end;
//函数块[2]:数据库
function FindString(SearthString: String): String;
begin
  if SearthString = '小虎牙V8卡车引擎(可选)' then
  begin
    Result := 'HySuperV8';
    Exit;
  end;
  if SearthString = '达夫(Daf)引擎声音(可选)' then
  begin
    Result := 'Daf';
    Exit;
  end;
  if SearthString = '雷诺(Renault)引擎声音(可选)' then
  begin
    Result := 'Renault';
    Exit;
  end;
  if SearthString = '斯堪尼亚(Scania)_DC12引擎声音(可选)' then
  begin
    Result := 'Scania_DC12';
    Exit;
  end;
  if SearthString = '斯堪尼亚(Scania)_DC124引擎声音(可选)' then
  begin
    Result := 'Scania_DC124';
    Exit;
  end;
  if SearthString = '斯堪尼亚(Scania)_v8引擎声音(可选)' then
  begin
    Result := 'Scania_v8';
    Exit;
  end;
  if SearthString = '沃尔沃(Volvo)引擎声音(可选)' then
  begin
    Result := 'Volvo_vnl';
    Exit;
  end;
  if SearthString = '小虎牙内部声音(可选)' then
  begin
    Result := 'HyInteralSound';
    Exit;
  end;
  if SearthString = '导航东北美眉(可选)' then
  begin
    Result := 'DongbeiMM';
    Exit;
  end;
  if SearthString = '导航甜蜜老张(可选)' then
  begin
    Result := 'Tianmilaozhang';
    Exit;
  end;
  if SearthString = '导航陈舒婷(可选)' then
  begin
    Result := 'Chenshuting';
    Exit;
  end;
  if SearthString = '导航郭德纲(可选)' then
  begin
    Result := 'Guodegang';
    Exit;
  end;
  if SearthString = '导航罗永浩(可选)' then
  begin
    Result := 'Luoyonghao';
    Exit;
  end;
  if SearthString = '导航沈腾(可选)' then
  begin
    Result := 'Shenteng';
    Exit;
  end;
  if SearthString = '导航穗穗(可选)' then
  begin
    Result := 'Suisui';
    Exit;
  end;
  if SearthString = '导航徐江(可选)' then
  begin
    Result := 'Xujiang';
    Exit;
  end;
  if SearthString = '导航于谦(可选)' then
  begin
    Result := 'Yuqian';
    Exit;
  end;
  if SearthString = '导航乐正凌(可选)' then
  begin
    Result := 'LeZhengLing';
    Exit;
  end;
  if SearthString = '导航五人(可选)' then
  begin
    Result := 'Wuren';
    Exit;
  end;
  if SearthString = '导航向晚(可选)' then
  begin
    Result := 'Xiangwan';
    Exit;
  end;
  if SearthString = '导航冰糖(可选)' then
  begin
    Result := 'Bingtang';
    Exit;
  end;
  if SearthString = '导航洛天依(可选)' then
  begin
    Result := 'Luotianyi';
    Exit;
  end;
  if SearthString = '导航林志玲(可选)' then
  begin
    Result := 'Linzhiling';
    Exit;
  end;
  if SearthString = '导航林志玲v2(可选)' then
  begin
    Result := 'Linzhiling_v2';
    Exit;
  end;
  if SearthString = '导航山兔(可选)' then
  begin
    Result := 'Shantu';
    Exit;
  end;
  if SearthString = '导航少年Pi(可选)' then
  begin
    Result := 'ShaonianPi';
    Exit;
  end;
  if SearthString = '导航小团团(可选)' then
  begin
    Result := 'Xiaotuantuan';
    Exit;
  end;
  if SearthString = '导航可莉(可选)' then
  begin
    Result := 'Keli';
    Exit;
  end;
  if SearthString = '导航茉莉(可选)' then
  begin
    Result := 'Moli';
    Exit;
  end; 
  if SearthString = '导航派蒙(可选)' then
  begin
    Result := 'Paimeng';
    Exit;
  end;
  if SearthString = '导航·琴(可选)' then
  begin
    Result := 'Qin';
    Exit;
  end
  else
  begin
    Result := 'None';
  end;
end;
//功能块[1,6]:播放背景音乐/获取游戏存档目录[1]
procedure InitializeWizard();
var
  //变量·播放背景音乐
  ErrorCode: HRESULT;
  ErrorText: WideString;
  MusicFilePath: String;
  //变量·获取游戏存档目录
  ExecCode: Integer;
begin
  //预解压需要的文件
  ExtractTemporaryFile('BackgroundMusic.mp3');
  ExtractTemporaryFile('PlaySound.png');
  ExtractTemporaryFile('C_ListProfile.bat');
  ExtractTemporaryFile('D_ListProfile.bat');
  ExtractTemporaryFile('E_ListProfile.bat');
  //按件属性
  //程序·播放背景音乐
  MusicFilePath:= ExpandConstant('{tmp}\BackgroundMusic.mp3');
  if FileExists(ExpandConstant('{tmp}\BackgroundMusic.mp3')) then
  begin
    if DSInitializeAudioFile(MusicFilePath, @OnEmbeddedMediaPlayerEvent) then
    begin
      DSSetVolume(-1000);
      DSPlayMediaFile;
    end
    else
    begin
        ErrorCode := DSGetLastError(ErrorText);
        MsgBox('错误: ' + IntToStr(ErrorCode) + ErrorText, mbError, MB_OK);
      end;
    end;
  //程序·获取游戏存档目录
  begin
    Exec(ExpandConstant('{tmp}\C_ListProfile.bat'), '', '', SW_SHOW, ewWaitUntilTerminated, ExecCode);
    if not FileExists(ExpandConstant('{localappdata}\Temp\Profiles.txt')) then 
    begin
      Exec(ExpandConstant('{tmp}\D_ListProfile.bat'), '', '', SW_SHOW, ewWaitUntilTerminated, ExecCode);
      if not FileExists(ExpandConstant('{localappdata}\Temp\Profiles.txt')) then 
      begin
        Exec(ExpandConstant('{tmp}\E_ListProfile.bat'), '', '', SW_SHOW, ewWaitUntilTerminated, ExecCode);
        if not FileExists(ExpandConstant('{localappdata}\Temp\Profiles.txt')) then 
        begin
          MsgBox('错误:-1,请以管理员模式启动!', mbError, MB_OK);
          Exit;
        end;
      end;
    end;
  end;
end;
//功能块[2,4,5]:获取游戏目录/写入选择的Bank/写入游戏声音[2]/清除安装残留
procedure CurPageChanged(CurPageID: Integer);  
var 
  //变量·获取游戏目录
  ReceiveInstallPathBool: Boolean;
  ReceiveInstallPath: String;
  //变量·写入选择的Bank
  i, ii: Integer;
  ComponentName: String;    
  BankFilePath: String;  
  BankText: String;  
  StringFindReceive: String;
  BankTextArray: TStringList;
  //变量· 清除注册表Name和Component项
  RegText: String;
  //变量·写入游戏声音大小
  TempProfilesPath, ProfilesText: String;
  TempProfiles, RealProfilesPath1, RealProfilesPath2, RealProfiles1, RealProfiles2: TStringList;
begin
  //程序·获取游戏目录
  if CurPageID = wpSelectDir then
  begin
    ReceiveInstallPathBool:= SearthGamePath(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 227300', 'InstallLocation', ReceiveInstallPath)
    if ReceiveInstallPathBool then
    begin
      if ReceiveInstallPath <> '' then
      begin
        WizardForm.DirEdit.Text:= ReceiveInstallPath;
      end;
    end
    else
      MsgBox('错误:-2,未找到游戏目录，请手动输入!', mbError, MB_OK);
      Exit;
  end;
  //程序·写入选择的Bank
  if CurPageID <> wpFinished then
  begin 
    Exit;  // 如果不是完成页面，则直接退出
  end
  else
  begin
    BankFilePath := ExpandConstant('{app}\bin\win_x64\plugins\ts-fmod-plugin\selected.bank.txt');  
    BankTextArray := TStringList.Create;  
    try  
    // 遍历所有组件  
    for i := 0 to WizardForm.ComponentsList.Items.Count - 1 do  
    begin
    // 检查组件是否被选中且不是Main或Option  
      if WizardForm.ComponentsList.Checked[i] then
      begin
        //获取选定组件Description
        ComponentName := WizardForm.ComponentsList.Items[i];
        //将ComponentName与数据库ID对比 
        begin
          StringFindReceive := FindString(ComponentName)
          if StringFindReceive <> 'None' then
          begin
            BankTextArray.add(StringFindReceive);
          end
          else
          begin
            Continue;
          end;
        end;
      end;
      // 如果已经选择了足够的组件，可以退出循环  
      if BankTextArray.Count >= 3 then  
        Break;  
    end;  
    //清空Bank选择内容
    BankText := '';
    //将选中的组件名称写入变量
    for i := 0 to BankTextArray.Count - 1 do  
    begin  
      BankText := BankText + BankTextArray[i] + #13#10;  
    end;  
    // 写入文件  
    if not SaveStringToFile(BankFilePath, BankText, False) then  
    begin  
      MsgBox('错误:-3,请以管理员模式启动!', mbError, MB_OK);
    end;  
    finally  
      BankTextArray.Free;  // 释放StringList
    end;
  end;
  //程序·写入游戏声音[2]
  begin
    try
    TempProfilesPath:= ExpandConstant('{localappdata}\Temp\Profiles.txt');
    TempProfiles:= TStringList.Create;
    RealProfilesPath1:= TStringList.Create;
    RealProfilesPath2:= TStringList.Create;
    RealProfiles1:= TStringList.Create;
    RealProfiles2:= TStringList.Create;
    TempProfiles.LoadFromFile(TempProfilesPath);
    for i:= 0 to TempProfiles.Count - 1 do
    begin
      RealProfilesPath1.Add(ExpandConstant('{userdocs}\Euro Truck Simulator 2\profiles\' + TempProfiles[i] + '\config.cfg'));
      RealProfilesPath2.Add(ExpandConstant('{userdocs}\Euro Truck Simulator 2\profiles\' + TempProfiles[i] + '\config_local.cfg'));
      RealProfiles1.LoadFromFile(RealProfilesPath1[i]);
      RealProfiles2.LoadFromFile(RealProfilesPath2[i]);
      ProfilesText:= '';
      for ii:= 0 to RealProfiles1.Count - 1 do
      begin
        if Pos('uset g_voice_navigation_pack', RealProfiles1[ii]) > 0 then
        begin
          RealProfiles1[ii]:= 'uset g_voice_navigation_pack "chinese_you"';
        end;
        if Pos('uset g_voice_navigation "0"', RealProfiles1[ii]) > 0 then
        begin
          RealProfiles1[ii]:= 'uset g_voice_navigation "1"';
        end;
        ProfilesText:= ProfilesText + RealProfiles1[ii] + #13#10;
      end;
      if not SaveStringToFile(RealProfilesPath1[i], ProfilesText, False) then
      begin
        MsgBox('错误:-4,请以管理员模式启动!', mbError, MB_OK);
      end;
      ProfilesText:= '';
      for ii:= 0 to RealProfiles2.Count - 1 do
      begin
        if Pos('uset s_navigation_volume', RealProfiles2[ii]) > 0 then
        RealProfiles2[ii]:= 'uset s_navigation_volume "0"';
        ProfilesText:= ProfilesText + RealProfiles2[ii] + #13#10;
      end;
      if not SaveStringToFile(RealProfilesPath2[i], ProfilesText, False) then
      begin
        MsgBox('错误:-4,请以管理员模式启动!', mbError, MB_OK);
      end;
      //写入Profiles声音
    end;
    finally
      TempProfiles.Free;
      RealProfilesPath1.Free;
      RealProfilesPath2.Free;
      RealProfiles1.Free;
      RealProfiles2.Free;
    end;
  end;
  //程序·清除安装残留
  begin
    //清除文件残留
    DeleteFile(ExpandConstant('{localappdata}\Temp\Profiles.txt'));
  end;
  begin
    //清除注册表残留
    RegText:= '';
    if RegWriteStringValue(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB59022F-93F0-40E4-8C82-413B4DB52BDF}_is1', 'Inno Setup: Deselected Components', RegText) then
    begin
      if not RegWriteStringValue(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EB59022F-93F0-40E4-8C82-413B4DB52BDF}_is1', 'Inno Setup: Selected Components', RegText) then
      begin
        MsgBox('错误:-10! 请以管理员模式启动!', mbError, MB_OK);
      end;
    end;  
  end;
end;
//功能块[3]:检查游戏文件夹
function NextButtonClick(CurPageID: Integer): Boolean;
var
CheakDirReceive: Boolean;
InstallPath:String;
begin
  Result:= True;
  if CurPageID = wpSelectDir then 
  begin 
    InstallPath := WizardDirValue + '\bin\win_x64\eurotrucks2.exe';
    CheakDirReceive := CheakDir(InstallPath)
    if not CheakDirReceive then
    begin  
      MsgBox('请选择带有Euro Truck Simulator 2的Common文件夹', mbError, MB_OK); 
      Result:= False
    end
    else
    begin
      Exit;
    end;
  end;
end;
//功能块[4]:结束播放音乐
procedure DeinitializeSetup;
begin
  DSStopMediaPlay;
end;